import React from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy - TikTok Wrapped',
  description: 'TikTok Wrapped Privacy Policy - Learn how we protect your privacy and handle your TikTok data. We do not store or share your uploaded files.',
  keywords: [
    'Privacy Policy',
    'TikTok Wrapped Privacy',
    'Data Protection',
    'Privacy',
    'User Privacy',
  ],
  openGraph: {
    title: 'Privacy Policy - TikTok Wrapped',
    description: 'TikTok Wrapped respects user privacy and is committed to protecting personal data.',
    url: 'https://ttwrapper.com/privacy',
  },
  alternates: {
    canonical: 'https://ttwrapper.com/privacy',
  },
}

export default function PrivacyPage() {
  return (
    <div className="container">
      <div className="card">
        <h1 className="section-title">Privacy Policy</h1>
        
        <div className="privacy-content">
          <p className="privacy-updated">
            <strong>Last updated:</strong> 29/12/2025
          </p>
          
          <p className="privacy-intro">
            TikTok Wrapped respects user privacy and is committed to protecting personal data.
          </p>

          <section className="privacy-section">
            <h2 className="privacy-section-title">Information We Process</h2>
            <p className="privacy-text">
              TikTok Wrapped processes only the information that users voluntarily upload in the form of their TikTok data export files. These files may contain personal activity information generated by TikTok.
            </p>
            <p className="privacy-text">
              We do not require account creation, personal identification, or contact details to use the service.
            </p>
          </section>

          <section className="privacy-section">
            <h2 className="privacy-section-title">How Data Is Used</h2>
            <p className="privacy-text">
              Uploaded files are used exclusively to:
            </p>
            <ul className="privacy-list">
              <li>analyze and summarize TikTok activity data,</li>
              <li>generate visual and statistical insights for the user.</li>
            </ul>
            <p className="privacy-text">
              Data is not used for advertising personalization, marketing profiling, or resale.
            </p>
          </section>

          <section className="privacy-section">
            <h2 className="privacy-section-title">Data Storage</h2>
            <p className="privacy-text">
              Uploaded files are processed automatically and are not permanently stored beyond what is technically necessary to provide the requested analysis. We do not build user profiles or databases from uploaded data.
            </p>
          </section>

          <section className="privacy-section">
            <h2 className="privacy-section-title">Third-Party Services</h2>
            <p className="privacy-text">
              The website may use standard analytics and advertising services (such as Google AdSense) to support site operation. These services may use cookies or similar technologies in accordance with their own privacy policies.
            </p>
            <p className="privacy-text">
              TikTok Wrapped does not share uploaded TikTok data with third parties.
            </p>
          </section>

          <section className="privacy-section">
            <h2 className="privacy-section-title">User Consent</h2>
            <p className="privacy-text">
              By uploading a file, users confirm that they own the data and consent to its processing for the purpose of generating insights.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}

